### ISSUE TITLE
Question: Why FriendlyName column length is NVARCHAR(449)

### ISSUE THREAD

**Issue by maximpashuk** [abwalters/AspNetCore.DataProtection.SqlServer#1]
src/AspNetCore.DataProtection.SqlServer/SqlServerXmlRepository.cs

449 is strange number, I don't get the purpose of this.
Can you explain this column length?

**Comment by adamrushad** [comment]
Absolutely.

That column is used as the primary key for the table. MSSQL has a maximum key length of 900 bytes, and due to that data being stored in Microsoft's semi-UTF16, where all characters are two bytes long (https://technet.microsoft.com/en-us/library/ms191241(v=sql.105).aspx). The maximum number of characters the column can support while being a key is 449, due to the requirement of the null terminator on the string. I could have made it smaller, I suppose, but 449 is as large as I could make it while keeping it as a key.

**Comment by maximpashuk** [comment]
Thanks for answering!
Now it is clear to me.
Closing my issue.
